name: Push
on:
  push:
    branches: 
      - master

jobs:
  codecheck:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Lock and install dependencies
      id: prep
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install -d

    - name: PyLint
      id: pylint
      run: | 
        pipenv run pylint -f colorized choco_py
